spring:
  threads:
    virtual:
      enabled: true

  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      write-concern:
        w: majority
        journal: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "org.innowise.internship.paymentservice.model.dto.messagerequest"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      properties:
        enable.idempotence: true

    listener:
      ack-mode: record
      concurrency: 5

mongock:
  enabled: true
  migration-scan-package:
    - org.innowise.internship.paymentservice.migrations
  migration-repository-name: mongockChangeLog
  lock-repository-name: mongockLock

app:
  kafka:
    topics:
      payment-requests:
        name: "payment-requests-topic"
        partitions: 3
        replicas: 3
      payment-results:
        name: "payment-results-topic"
        partitions: 3
        replicas: 3
    inbox:
      processing-delay: 100
      batch-size: 100
      days-to-store-records: 3
    outbox:
      publish-delay: 100
      batch-size: 100
      days-to-store-records: 3
      retries: 5

server:
  port: ${SERVER_PORT}