apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.0
          env:
            - name: KAFKA_PORT
              value: ""
          envFrom:
            - configMapRef:
                name: kafka-config-map
          ports:
            - containerPort: 9092
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 90
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 90
            periodSeconds: 20
      restartPolicy: Always