apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: payment-pv
  resources:
    requests:
      storage: 512Mi