apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/volumes/payment_db_volume